package chatroom.model.message;

public enum MessageType {
    PUBLICSERVERMSG, PUBLICTEXTMSG, TARGETTEXTMSG, LOGINMSG, LOGOUTMSG, TARGETSERVERMSG, LOGINRESPONSEMSG, ROOMLISTMSG,
    ROOMUSERLISTMSG, ROOMCHANGEREQMSG, WARNINGMSG, SERVERUSERLISTMSG, ROOMCHANGERESPONSEMSG, ROOMNAMEEDITMSG
}